services:
  # Database Bán hàng
  mysql_db:
    image: mysql:8.0
    container_name: noah_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webstore
    volumes:
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - noah_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Tài chính
  postgres_db:
    image: postgres:15
    container_name: noah_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance
    networks:
      - noah_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finance"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Trạm tin nhắn
  rabbitmq:
    image: rabbitmq:3-management
    container_name: noah_rabbitmq
    networks:
      - noah_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Gateway bảo mật
  kong:
    image: kong:latest
    container_name: noah_kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./docs/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
    networks:
      - noah_network

  # Con Bot của Nhi
  legacy_adapter:
    build:
      context: .
      dockerfile: ./modules/module-1/Dockerfile
    container_name: legacy_adapter
    volumes:
      - ./app/input:/app/input
      - ./app/processed:/app/processed
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - noah_network

  # Thành phần 2A (Order API)
  order_api:
    build:
      context: ./modules/module-2a
      dockerfile: Dockerfile
    container_name: order_api
    ports:
      - "8001:8000"
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - noah_network

  # Thành phần 2B (Order Worker)
  order_worker:
    build:
      context: ./modules/module-2b
      dockerfile: Dockerfile
    container_name: order_worker
    depends_on:
      mysql_db:
        condition: service_healthy
      postgres_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - noah_network

networks:
  noah_network:
    driver: bridge
